kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  namespace: my-namespace
spec:
  type: NodePort       # or NodePort
  selector:
    app: zomato
  ports:
    - port: 9100
      targetPort: 9100


