apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: my-namespace
  labels:
    app: zomato
spec:
  selector:
    app: zomato
  ports:
    - name: http-metrics
      port: 9100
      targetPort: 9100
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-app-monitor
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: zomato
  namespaceSelector:
    matchNames: ["my-namespace"]
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s


