apiVersion: v1
kind: Service
metadata:
  name: node-exporter          # you can also rename to zomato-metrics
  namespace: my-namespace
spec:
  selector:
    app: zomato                # match your pods' label
  ports:
    - name: http-metrics
      port: 9100
      targetPort: 9100         # container must listen on 9100
      protocol: TCP
  type: ClusterIP


