kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  namespace: my-namespace
spec:
  selector:
    name: node-exporter      # must match pod label
  ports:
    - name: http-metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
  type: NodePort            # NodePort not needed for Prometheus inside cluster
